# config for travis-ci
language: python
sudo: false
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"  
install:
  # gcut version
  - "ls /usr/lib/x86_64-linux-gnu/libboost_*"
  - "pip install -r requirements-dev.txt"
  - "pip install -v -e ."
script: true
addons:
  apt:
    packages:
    - build-essential    
    - libboost-python-dev
cache:
- apt
- directories:
  - "$HOME/.cache/pip"
script:
  - nosetests tests/filter_/
#  - nosetests tests/io_/
#  - nosetests tests/features_/
