# This workflow will install Python dependencies, the package, and run the tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and test (w graphcut)

on:
  push:
    branches: [ "master", "Release*" ]
  pull_request:
    branches: [ "master", "Release*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies for graphcut functionality
      run: sudo apt-get install -y libboost-python-dev build-essential
    - name: Locate libboost
      run: |
        cat /etc/ld.so.conf.d/*
        ls /usr/lib/x86_64-linux-gnu/libboost_*
        ls /lib/x86_64-linux-gnu/libboost_*
#    - name: Install with test dependencies
#      run: |
#        python -m pip install --upgrade pip
#        python -m pip install -v .[test]
#    - name: Test with pytest
#      run: pytest tests/graphcut_/*
